---
abstract: 'A minimalistic deploy tool'
author:
  - 'Kentaro Kuribayashi E<lt>kentarok@gmail.comE<gt>'
build_requires:
  Capture::Tiny: 0
  Directory::Scratch: 0
  Test::Class: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cinnamon
no_index:
  directory:
    - inc
provides:
  Cinnamon:
    file: lib/Cinnamon.pm
    version: 0.03
  Cinnamon::CLI:
    file: lib/Cinnamon/CLI.pm
    version: 0
  Cinnamon::Config:
    file: lib/Cinnamon/Config.pm
    version: 0
  Cinnamon::Config::Loader:
    file: lib/Cinnamon/Config/Loader.pm
    version: 0
  Cinnamon::DSL:
    file: lib/Cinnamon/DSL.pm
    version: 0
  Cinnamon::Local:
    file: lib/Cinnamon/Local.pm
    version: 0
  Cinnamon::Logger:
    file: lib/Cinnamon/Logger.pm
    version: 0
  Cinnamon::Remote:
    file: lib/Cinnamon/Remote.pm
    version: 0
  Cinnamon::Runner:
    file: lib/Cinnamon/Runner.pm
    version: 0
requires:
  AnyEvent: 0
  Class::Load: 0
  Getopt::Long::Parser: 0
  IPC::Run: 0
  Log::Dispatch: 0
  Net::OpenSSH: 0
  POSIX: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  parent: 0
  perl: 5.014002
resources:
  X_prepan:
    author_url: http://prepan.org/user/xxxxxxx
    module_url: http://prepan.org/module/xxxxx
version: 0.03
