---
abstract: 'A minimalistic deploy tool'
author:
  - '=over 4'
build_requires:
  Capture::Tiny: 0
  Cwd::Guard: 0
  Directory::Scratch: 0
  Test::Class: 0
  Test::Fatal: 0
  Test::Mock::Guard: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.5, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cinnamon
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Cinnamon:
    file: lib/Cinnamon.pm
    version: 0.26
  Cinnamon::CLI:
    file: lib/Cinnamon/CLI.pm
  Cinnamon::Config::Loader:
    file: lib/Cinnamon/Config/Loader.pm
  Cinnamon::Context:
    file: lib/Cinnamon/Context.pm
  Cinnamon::DSL:
    file: lib/Cinnamon/DSL.pm
  Cinnamon::HandleManager:
    file: lib/Cinnamon/HandleManager.pm
  Cinnamon::Local:
    file: lib/Cinnamon/Local.pm
  Cinnamon::Logger:
    file: lib/Cinnamon/Logger.pm
  Cinnamon::Remote:
    file: lib/Cinnamon/Remote.pm
  Cinnamon::Role:
    file: lib/Cinnamon/Role.pm
  Cinnamon::Runner:
    file: lib/Cinnamon/Runner.pm
  Cinnamon::Task:
    file: lib/Cinnamon/Task.pm
requires:
  AnyEvent: 0
  Class::Load: 0
  Coro: 0
  Getopt::Long: 0
  Hash::MultiValue: 0
  IPC::Run: 0
  Log::Dispatch: 0
  Moo: 0
  Net::OpenSSH: 0
  POSIX: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  YAML: 0
  parent: 0
  perl: 5.014002
resources:
  bugtracker: https://github.com/kentaro/cinnamon/issues
  homepage: https://github.com/kentaro/cinnamon
  repository: git://github.com/kentaro/cinnamon.git
version: 0.26
x_contributors:
  - 'wakabatan <wakabatan@localhost.localdomain>'
  - 'hatyuki <hatyuki29@gmail.com>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'hayajo <hayajo@cpan.org>'
  - 'Kentaro Kuribayashi <kentarok@gmail.com>'
  - 'TERAOKA Yoshinori <yteraoka@me.com>'
  - 'mechairoi <ttsujikawa@gmail.com>'
  - 'shibayu36 <shibayu36@gmail.com>'
