---
abstract: 'A minimalistic deploy tool'
author:
  - 'Yuki Shibazaki <shibayu36@gmail.com>'
  - 'Kentaro Kuribayashi kentarok@gmail.com'
build_requires:
  Capture::Tiny: 0
  Cwd::Guard: 0
  Directory::Scratch: 0
  Test::Class: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cinnamon
no_index:
  directory:
    - inc
provides:
  Cinnamon:
    file: lib/Cinnamon.pm
    version: 0.13_01
  Cinnamon::CLI:
    file: lib/Cinnamon/CLI.pm
  Cinnamon::Config:
    file: lib/Cinnamon/Config.pm
  Cinnamon::Config::Loader:
    file: lib/Cinnamon/Config/Loader.pm
  Cinnamon::DSL:
    file: lib/Cinnamon/DSL.pm
  Cinnamon::HandleManager:
    file: lib/Cinnamon/HandleManager.pm
  Cinnamon::Local:
    file: lib/Cinnamon/Local.pm
  Cinnamon::Logger:
    file: lib/Cinnamon/Logger.pm
  Cinnamon::Remote:
    file: lib/Cinnamon/Remote.pm
  Cinnamon::Runner:
    file: lib/Cinnamon/Runner.pm
  Cinnamon::Runner::Concurrent:
    file: lib/Cinnamon/Runner/Concurrent.pm
requires:
  AnyEvent: 0
  Class::Load: 0
  Coro: 0
  Getopt::Long: 0
  IPC::Run: 0
  Log::Dispatch: 0
  Net::OpenSSH: 0
  POSIX: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  YAML: 0
  parent: 0
  perl: 5.014002
resources:
  license: http://dev.perl.org/licenses/
version: 0.13_01
